cameraL:
    uri: http://www.vetprofessionals.com/catprofessional/images/home-cat.jpg
    K: [0]
    H: [0]
    map: [0]
cameraR:
    uri: http://www.vetprofessionals.com/catprofessional/images/home-cat.jpg
    K: [0]
    H: [0]
    map: [0]
frame_range: [0, 10]

