cameraL:
    uri: /Users/kyoheee/Documents/MATLAB/JPLTerrain/DATA/ATRVJR_DATA/ATRVJR_BEDROCK01/img/L{:06d}.png
    f: 487.7632
    uv0: [319.5, 239.5]
    uri_map: lutL.png
cameraR:
    uri: /Users/kyoheee/Documents/MATLAB/JPLTerrain/DATA/ATRVJR_DATA/ATRVJR_BEDROCK01/img/R{:06d}.png
    f: 487.7632
    uv0: [319.5, 239.5]
    uri_map: lutR.png
frame_range: [0, 300]

