version: 1
formatters:
    simple:
        format: '%(asctime)s %(message)s'
        #datefmt: '%Y-%m-%dT%H:%M:%S'
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
    file_adc:
        class : logging.handlers.RotatingFileHandler
        formatter: simple
        #filename: /home/kubotalab/FieldData/Oshima2015/Day1/adc.log
        filename: log/adc.log
        maxBytes: 10240000
        backupCount: 1000
    file_dynpick:
        class : logging.handlers.RotatingFileHandler
        formatter: simple
        filename: log/dynpick.log
        maxBytes: 10240000
        backupCount: 1000
    file_compass:
        class : logging.handlers.RotatingFileHandler
        formatter: simple
        filename: log/compass.log
        maxBytes: 10240000
        backupCount: 1000
loggers:
    logger_adc:
        level: DEBUG
        handlers: [file_adc]
        propagate: no
    logger_dynpick:
        level: DEBUG
        handlers: [file_dynpick]
        propagate: no
    logger_compass:
        level: DEBUG
        handlers: [file_compass]
        propagate: no
root:
    level: DEBUG
    handlers: [file_compass]

